name: Playwright Tests in Docker

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  playwright-tests:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Run Playwright tests inside Docker
      - name: Run Playwright tests
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/e2e \
            -w /e2e \
            -e BASE_URL=${{ secrets.BASE_URL }} \
            mcr.microsoft.com/playwright:focal \
            sh -c "npm install && npx playwright install && npx playwright test --reporter=html"

      # 3. Upload HTML report as artifact
      - name: Upload Playwright HTML report
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
